Fix nisra logo on mobile
ONSdigital/census-website-generator pull request #133
Opened 2020-11-24 09:36 UTC by boxadesign

## Context 
- BUG - Stacked ONS logo showing on < 500px

## Review
- Check that correct logo displays on <500px viewport across all 3 sites.

2020-11-26 21:43 UTC, kruncher approved these changes

2020-11-26 21:45 UTC, kruncher requested changes
Needs to be rebased from master.

2020-11-26 22:05 UTC, kruncher approved these changes

2020-11-27 09:10 UTC, georgecodes approved these changes

2020-11-27 09:58 UTC, merged